[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.serve-helper]
run_task = { name = "release", fork = true }

[tasks.serve]
workspace = false
script = '''
cd ./target/release/
./reshare-server
'''
dependencies = ["serve-helper"]
